
import helper.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {
    Connection connection = Koneksi.getConnection();
    
    private String nip="", jabatan="", nama="", noStruk="", tanggal="";
    private int gaji=0;
    private double lembur=0, tunjangan=0, total=0;
    private boolean isActiveDelMode = false;
    
    private static final Map<String, String> dataPegawai = new HashMap<String, String>(){{
        put("D001", "DILA ANNISA");
        put("D002", "DAIS CAHYAWATIE");
        put("D003", "DIKA PRAYOGA");
        put("D004", "WINDA ANDINI");
        put("D005", "NAMIRA PUTRI");
    }};
    
    
    private static final Map<String, Integer> jabatanGaji = new HashMap<String, Integer>(){{
        put("KEPALA", 1000000);
        put("BENDAHARA", 700000);
        put("SEKRETARIS", 700000);
        put("STAFF", 650000);
    }};
    
    private boolean isFormValid(){
        if(this.noStruk.isEmpty()){
            return false;
        }
        if(this.tanggal.isEmpty()){
            return false;
        }
        if(this.nip.isEmpty()){
            return false;
        }
        if(this.nama.isEmpty()){
            return false;
        }
        if(this.jabatan.isEmpty()){
            return false;
        }
        if(this.gaji == 0){
            return false;
        }
        if(this.total == 0){
            return false;
        }
        return true;
    }
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header_zamzamsb = new javax.swing.JPanel();
        title_zamzamsb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        form_zamzamsb = new javax.swing.JPanel();
        labelNoStruk_zamzamsb = new javax.swing.JLabel();
        noStruk_zamzamsb = new javax.swing.JTextField();
        labelTanggal_zamzamsb = new javax.swing.JLabel();
        tanggal_zamzamsb = new javax.swing.JTextField();
        labelNip_zamzamsb = new javax.swing.JLabel();
        nip_zamzamsb = new javax.swing.JComboBox<>();
        labelNama_zamzamsb = new javax.swing.JLabel();
        nama_zamzamsb = new javax.swing.JTextField();
        labelJabatan_zamzamsb = new javax.swing.JLabel();
        jabatan_zamzamsb = new javax.swing.JComboBox<>();
        labelGaji_zamzamsb = new javax.swing.JLabel();
        gaji_zamzamsb = new javax.swing.JTextField();
        labelLembur_zamzamsb = new javax.swing.JLabel();
        lembur_zamzamsb = new javax.swing.JTextField();
        tunjangan_zamzamsb = new javax.swing.JTextField();
        labelTunjangan_zamzamsb = new javax.swing.JLabel();
        total_zamzamsb = new javax.swing.JTextField();
        labelTotal_zamzamsb = new javax.swing.JLabel();
        addNew_zamzamsb = new javax.swing.JButton();
        clearData_zamzamsb = new javax.swing.JButton();
        save_zamzamsb = new javax.swing.JButton();
        close_zamzamsb = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_zamzamsb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROJECT_ZAM ZAM SAEFUL BAHTIAR");
        setBackground(null);

        header_zamzamsb.setBackground(new java.awt.Color(255, 255, 255));
        header_zamzamsb.setForeground(null);

        title_zamzamsb.setBackground(new java.awt.Color(255, 255, 255));
        title_zamzamsb.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        title_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        title_zamzamsb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_zamzamsb.setText("PENGGAJIAN KECAMATAN BANJARSARI");
        title_zamzamsb.setToolTipText("JUDUL");

        javax.swing.GroupLayout header_zamzamsbLayout = new javax.swing.GroupLayout(header_zamzamsb);
        header_zamzamsb.setLayout(header_zamzamsbLayout);
        header_zamzamsbLayout.setHorizontalGroup(
            header_zamzamsbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_zamzamsbLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(title_zamzamsb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113))
        );
        header_zamzamsbLayout.setVerticalGroup(
            header_zamzamsbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_zamzamsbLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title_zamzamsb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        form_zamzamsb.setBackground(new java.awt.Color(255, 255, 255));
        form_zamzamsb.setForeground(null);

        labelNoStruk_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelNoStruk_zamzamsb.setText("No Struk");

        noStruk_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        noStruk_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        noStruk_zamzamsb.setToolTipText("");
        noStruk_zamzamsb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noStruk_zamzamsbKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noStruk_zamzamsbKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noStruk_zamzamsbKeyReleased(evt);
            }
        });

        labelTanggal_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelTanggal_zamzamsb.setText("Tanggal");

        tanggal_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        tanggal_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        tanggal_zamzamsb.setToolTipText("");
        tanggal_zamzamsb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tanggal_zamzamsbKeyReleased(evt);
            }
        });

        labelNip_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelNip_zamzamsb.setText("NIP");

        nip_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        nip_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        nip_zamzamsb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih", "D001", "D002", "D003", "D004", "D005" }));
        nip_zamzamsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nip_zamzamsbActionPerformed(evt);
            }
        });

        labelNama_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelNama_zamzamsb.setText("Nama");

        nama_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        nama_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        nama_zamzamsb.setToolTipText("");

        labelJabatan_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelJabatan_zamzamsb.setText("Jabatan");

        jabatan_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        jabatan_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        jabatan_zamzamsb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih", "KEPALA", "BENDAHARA", "SEKRETARIS", "STAFF" }));
        jabatan_zamzamsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatan_zamzamsbActionPerformed(evt);
            }
        });

        labelGaji_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelGaji_zamzamsb.setText("Gaji Pokok");

        gaji_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        gaji_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        gaji_zamzamsb.setToolTipText("");

        labelLembur_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelLembur_zamzamsb.setText("Lembur");

        lembur_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        lembur_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        lembur_zamzamsb.setToolTipText("");
        lembur_zamzamsb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lembur_zamzamsbKeyReleased(evt);
            }
        });

        tunjangan_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        tunjangan_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        tunjangan_zamzamsb.setToolTipText("");
        tunjangan_zamzamsb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tunjangan_zamzamsbKeyReleased(evt);
            }
        });

        labelTunjangan_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelTunjangan_zamzamsb.setText("Tunjangan");

        total_zamzamsb.setBackground(new java.awt.Color(241, 244, 247));
        total_zamzamsb.setForeground(new java.awt.Color(10, 37, 64));
        total_zamzamsb.setToolTipText("");

        labelTotal_zamzamsb.setForeground(new java.awt.Color(66, 84, 102));
        labelTotal_zamzamsb.setText("Total Gaji");

        addNew_zamzamsb.setBackground(new java.awt.Color(10, 37, 64));
        addNew_zamzamsb.setForeground(new java.awt.Color(255, 255, 255));
        addNew_zamzamsb.setText("Data Baru");
        addNew_zamzamsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNew_zamzamsbActionPerformed(evt);
            }
        });

        clearData_zamzamsb.setBackground(new java.awt.Color(167, 37, 64));
        clearData_zamzamsb.setForeground(new java.awt.Color(255, 255, 255));
        clearData_zamzamsb.setText("Hapus");
        clearData_zamzamsb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearData_zamzamsbMouseClicked(evt);
            }
        });
        clearData_zamzamsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearData_zamzamsbActionPerformed(evt);
            }
        });

        save_zamzamsb.setBackground(new java.awt.Color(10, 111, 64));
        save_zamzamsb.setForeground(new java.awt.Color(255, 255, 255));
        save_zamzamsb.setText("Simpan");
        save_zamzamsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_zamzamsbActionPerformed(evt);
            }
        });

        close_zamzamsb.setBackground(new java.awt.Color(66, 84, 102));
        close_zamzamsb.setForeground(new java.awt.Color(255, 255, 255));
        close_zamzamsb.setText("Keluar");
        close_zamzamsb.setToolTipText("");
        close_zamzamsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_zamzamsbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout form_zamzamsbLayout = new javax.swing.GroupLayout(form_zamzamsb);
        form_zamzamsb.setLayout(form_zamzamsbLayout);
        form_zamzamsbLayout.setHorizontalGroup(
            form_zamzamsbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_zamzamsbLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(form_zamzamsbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jabatan_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nip_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNew_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotal_zamzamsb)
                    .addComponent(tunjangan_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTunjangan_zamzamsb)
                    .addComponent(lembur_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLembur_zamzamsb)
                    .addComponent(gaji_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGaji_zamzamsb)
                    .addComponent(labelJabatan_zamzamsb)
                    .addComponent(nama_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama_zamzamsb)
                    .addComponent(labelNip_zamzamsb)
                    .addComponent(tanggal_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTanggal_zamzamsb)
                    .addComponent(noStruk_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoStruk_zamzamsb)
                    .addComponent(clearData_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        form_zamzamsbLayout.setVerticalGroup(
            form_zamzamsbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_zamzamsbLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelNoStruk_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noStruk_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTanggal_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNip_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nip_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(labelNama_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJabatan_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jabatan_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelGaji_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaji_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelLembur_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lembur_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTunjangan_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tunjangan_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal_zamzamsb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(addNew_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearData_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(form_zamzamsb);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        table_zamzamsb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Struk", "Tanggal", "NIP", "Nama", "Jabatan", "Gaji Pokok", "Lembur", "Tunjangan", "Gaji Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_zamzamsb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_zamzamsbMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_zamzamsb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header_zamzamsb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_zamzamsb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1177, 982));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nip_zamzamsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nip_zamzamsbActionPerformed
        // TODO add your handling code here:
        if(nip_zamzamsb.getSelectedIndex() != 0){
            this.setNip(nip_zamzamsb.getSelectedItem().toString());
        }
    }//GEN-LAST:event_nip_zamzamsbActionPerformed

    private void jabatan_zamzamsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatan_zamzamsbActionPerformed
        // TODO add your handling code here:
        if(jabatan_zamzamsb.getSelectedIndex() != 0){
            this.setJabatan(jabatan_zamzamsb.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jabatan_zamzamsbActionPerformed

    private void noStruk_zamzamsbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noStruk_zamzamsbKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_noStruk_zamzamsbKeyPressed

    private void noStruk_zamzamsbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noStruk_zamzamsbKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_noStruk_zamzamsbKeyTyped

    private void noStruk_zamzamsbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noStruk_zamzamsbKeyReleased
        // TODO add your handling code here:
        this.setNoStruk(noStruk_zamzamsb.getText());
    }//GEN-LAST:event_noStruk_zamzamsbKeyReleased

    private void tanggal_zamzamsbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tanggal_zamzamsbKeyReleased
        // TODO add your handling code here:
        this.setTanggal(tanggal_zamzamsb.getText());
    }//GEN-LAST:event_tanggal_zamzamsbKeyReleased

    private void lembur_zamzamsbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lembur_zamzamsbKeyReleased
        // TODO add your handling code here:
        this.setLembur(Double.valueOf(lembur_zamzamsb.getText()));
    }//GEN-LAST:event_lembur_zamzamsbKeyReleased

    private void tunjangan_zamzamsbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tunjangan_zamzamsbKeyReleased
        // TODO add your handling code here:
        this.setTunjangan(Double.valueOf(tunjangan_zamzamsb.getText()));
    }//GEN-LAST:event_tunjangan_zamzamsbKeyReleased

    private void addNew_zamzamsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNew_zamzamsbActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_addNew_zamzamsbActionPerformed

    private void close_zamzamsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_zamzamsbActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_close_zamzamsbActionPerformed

    private void save_zamzamsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_zamzamsbActionPerformed
        // TODO add your handling code here:
        if(this.isFormValid()){
            this.insertData();
        }else{
            JOptionPane.showMessageDialog(null, "Silahkan isi terlebih dahulu!");
        }
    }//GEN-LAST:event_save_zamzamsbActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void table_zamzamsbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_zamzamsbMouseClicked
        // TODO add your handling code here:
        int row = table_zamzamsb.getSelectedRow();
        this.noStruk = table_zamzamsb.getValueAt(row, 1).toString();
        noStruk_zamzamsb.setText(this.noStruk);
        noStruk_zamzamsb.setEnabled(false);
        this.isActiveDelMode = true;
    }//GEN-LAST:event_table_zamzamsbMouseClicked

    private void clearData_zamzamsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearData_zamzamsbActionPerformed
        // TODO add your handling code here:
        if(this.isActiveDelMode){
            this.deleteDate();
        }
    }//GEN-LAST:event_clearData_zamzamsbActionPerformed

    private void clearData_zamzamsbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearData_zamzamsbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clearData_zamzamsbMouseClicked
    private void setTotal(int pokok, double tunjangan, double lembur){
        this.total = Double.valueOf(pokok) + tunjangan + lembur;
        total_zamzamsb.setEnabled(false);
        total_zamzamsb.setText(String.valueOf(this.total));
    }
    private void setTunjangan(double tunjangan){
        this.tunjangan = tunjangan;
        this.setTotal(this.gaji, this.tunjangan, this.lembur);
    }
    private void setLembur(double lembur){
        this.lembur = lembur;
        this.setTotal(this.gaji, this.tunjangan, this.lembur);
    }
    private void setTanggal(String tanggal){
        this.tanggal = tanggal;
    }
    private void setNoStruk(String noStruk){
        this.noStruk = noStruk;
    }
    private void setNip(String nip){
        this.nip = nip;
        // set nama
        this.setNama(dataPegawai.get(nip));
        
    }
    private void setJabatan(String jabatan){
        this.jabatan = jabatan;
        // set gaji
        this.setGaji(jabatanGaji.get(jabatan));
        
    }
    private void setNama(String nama){
         this.nama = nama;
         nama_zamzamsb.setText(nama);
         nama_zamzamsb.setEnabled(false);
    }
    private void setGaji(int gaji){
        this.gaji = gaji;
        gaji_zamzamsb.setText(String.valueOf(gaji));
        gaji_zamzamsb.setEnabled(false);
        this.setTotal(this.gaji, this.tunjangan, this.lembur);
    }
    private void clearForm(){
        gaji_zamzamsb.setText("");
        this.gaji = 0;
        lembur_zamzamsb.setText("");
        this.lembur = 0;
        nama_zamzamsb.setText("");
        this.nama = "";
        nip_zamzamsb.setSelectedIndex(0);
        this.nip = "";
        noStruk_zamzamsb.setText("");
        this.noStruk = "";
        tanggal_zamzamsb.setText("");
        this.tanggal = "";
        total_zamzamsb.setText("");
        this.total = 0;
        tunjangan_zamzamsb.setText("");
        this.tunjangan = 0;
        jabatan_zamzamsb.setSelectedIndex(0);
        this.jabatan = "";
        this.isActiveDelMode = false;
        noStruk_zamzamsb.setEnabled(true);
        this.getData();
    }
    private void insertData(){
        String sql = "INSERT INTO gaji (no_struk, tanggal, nip, nama, jabatan, gaji, lembur, tunjangan, total)"
                + "VALUES ('"+this.noStruk+"','"+ this.tanggal +"',"
                + "'"+ this.nip +"','"+ this.nama+"','"+ this.jabatan +"',"
                + "'"+String.valueOf(this.gaji) +"','"+ String.valueOf(this.lembur)  +"','"+ String.valueOf(this.tunjangan) +"','"+ String.valueOf(this.total) +"')";
        
        try{
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan data!");
            this.clearForm();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
        }
    }
    private void getData(){
        String sql = "SELECT * FROM gaji";
        try{
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet res = pst.executeQuery();
            
            DefaultTableModel dtm = (DefaultTableModel)table_zamzamsb.getModel();
            dtm.setRowCount(0);
            int baris = 1;
            String[] data = new String[10];
            while(res.next()){
                data[0] = String.valueOf(baris);
                data[1] = res.getString("no_struk");
                data[2] = res.getString("tanggal");
                data[3] = res.getString("nip");
                data[4] = res.getString("nama");
                data[5] = res.getString("jabatan");
                data[6] = res.getString("gaji");
                data[7] = res.getString("lembur");
                data[8] = res.getString("tunjangan");
                data[9] = res.getString("total");
                baris++;
                dtm.addRow(data);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal mengambil data: " + e.getMessage());
        }
    }
    private void deleteDate(){
        String sql = "DELETE FROM gaji WHERE "
                + "no_struk = ('"+this.noStruk+"')";
        
        try{
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Berhasil menghapus data!");
            this.clearForm();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNew_zamzamsb;
    private javax.swing.JButton clearData_zamzamsb;
    private javax.swing.JButton close_zamzamsb;
    private javax.swing.JPanel form_zamzamsb;
    private javax.swing.JTextField gaji_zamzamsb;
    private javax.swing.JPanel header_zamzamsb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jabatan_zamzamsb;
    private javax.swing.JLabel labelGaji_zamzamsb;
    private javax.swing.JLabel labelJabatan_zamzamsb;
    private javax.swing.JLabel labelLembur_zamzamsb;
    private javax.swing.JLabel labelNama_zamzamsb;
    private javax.swing.JLabel labelNip_zamzamsb;
    private javax.swing.JLabel labelNoStruk_zamzamsb;
    private javax.swing.JLabel labelTanggal_zamzamsb;
    private javax.swing.JLabel labelTotal_zamzamsb;
    private javax.swing.JLabel labelTunjangan_zamzamsb;
    private javax.swing.JTextField lembur_zamzamsb;
    private javax.swing.JTextField nama_zamzamsb;
    private javax.swing.JComboBox<String> nip_zamzamsb;
    private javax.swing.JTextField noStruk_zamzamsb;
    private javax.swing.JButton save_zamzamsb;
    private javax.swing.JTable table_zamzamsb;
    private javax.swing.JTextField tanggal_zamzamsb;
    private javax.swing.JLabel title_zamzamsb;
    private javax.swing.JTextField total_zamzamsb;
    private javax.swing.JTextField tunjangan_zamzamsb;
    // End of variables declaration//GEN-END:variables

}
